"""add search_mode and min_similarity to users

Revision ID: 1c856331e1b4
Revises: 3a47ce3db60c
Create Date: 2026-04-11 20:54:33.913626

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c856331e1b4'
down_revision: str | Sequence[str] | None = '3a47ce3db60c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_mode', sa.String(length=20), server_default='exact_tags', nullable=False))
    op.add_column('users', sa.Column('min_similarity', sa.Float(), server_default='0.3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'min_similarity')
    op.drop_column('users', 'search_mode')
    # ### end Alembic commands ###
