"""add agent created_by column

Revision ID: 398f94df1bee
Revises: 665994aa9019
Create Date: 2026-04-11 19:44:43.941151

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '398f94df1bee'
down_revision: str | Sequence[str] | None = '665994aa9019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agents', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'created_by')
    # ### end Alembic commands ###
