"""add conversation_turns and session context

Revision ID: 4a7477a0eb52
Revises: 639b70367a96
Create Date: 2026-04-07 14:52:14.915524

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a7477a0eb52'
down_revision: str | Sequence[str] | None = '639b70367a96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['match_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('match_sessions', sa.Column('match_context', sa.Text(), nullable=False))
    op.add_column('match_sessions', sa.Column('max_turns', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_sessions', 'max_turns')
    op.drop_column('match_sessions', 'match_context')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
