"""add affinity scoring columns

Revision ID: 5826086a64c4
Revises: 398f94df1bee
Create Date: 2026-04-11 20:08:37.950319

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5826086a64c4'
down_revision: str | Sequence[str] | None = '398f94df1bee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_sessions', sa.Column('affinity_score', sa.Float(), nullable=True))
    op.add_column('match_sessions', sa.Column('affinity_summary', sa.Text(), nullable=True))
    op.add_column('match_sessions', sa.Column('affinity_recommendation', sa.String(length=20), nullable=True))
    op.add_column('match_sessions', sa.Column('affinity_checked_at', sa.DateTime(), nullable=True))
    op.add_column('match_sessions', sa.Column('user_a_affinity_response', sa.String(length=20), nullable=True))
    op.add_column('match_sessions', sa.Column('user_b_affinity_response', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_sessions', 'user_b_affinity_response')
    op.drop_column('match_sessions', 'user_a_affinity_response')
    op.drop_column('match_sessions', 'affinity_checked_at')
    op.drop_column('match_sessions', 'affinity_recommendation')
    op.drop_column('match_sessions', 'affinity_summary')
    op.drop_column('match_sessions', 'affinity_score')
    # ### end Alembic commands ###
