"""add user profile columns

Revision ID: 665994aa9019
Revises: 4a7477a0eb52
Create Date: 2026-04-11 19:20:11.504900

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '665994aa9019'
down_revision: str | Sequence[str] | None = '4a7477a0eb52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('job', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('suburb', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('find_radius_m', sa.Integer(), server_default='500', nullable=False))
    op.add_column('users', sa.Column('allow_1on1_chat', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('allow_group_chat', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('tier', sa.String(length=20), server_default='free', nullable=False))
    op.add_column('users', sa.Column('preferred_model', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('auto_approve_affinity', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('default_max_turns', sa.Integer(), server_default='100', nullable=False))
    op.add_column('users', sa.Column('affinity_check_turns', sa.Integer(), server_default='20', nullable=False))
    op.add_column('users', sa.Column('max_concurrent_chats', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_concurrent_chats')
    op.drop_column('users', 'affinity_check_turns')
    op.drop_column('users', 'default_max_turns')
    op.drop_column('users', 'auto_approve_affinity')
    op.drop_column('users', 'preferred_model')
    op.drop_column('users', 'tier')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_visible')
    op.drop_column('users', 'allow_group_chat')
    op.drop_column('users', 'allow_1on1_chat')
    op.drop_column('users', 'find_radius_m')
    op.drop_column('users', 'suburb')
    op.drop_column('users', 'job')
    op.drop_column('users', 'age')
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###
