"""add visit_sessions and direct_messages tables

Revision ID: 77b773951fb1
Revises: 44769eeeef7f
Create Date: 2026-04-18 09:00:02.440977

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77b773951fb1'
down_revision: str | Sequence[str] | None = '44769eeeef7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visitor_x', sa.Integer(), nullable=True),
    sa.Column('visitor_y', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_sessions_host_active', 'visit_sessions', ['host_id', 'status'], unique=False)
    op.create_index('ix_visit_sessions_visitor_active', 'visit_sessions', ['visitor_id', 'status'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_session_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_session_id'], ['visit_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_direct_messages_session_created', 'direct_messages', ['visit_session_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('island_seed', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('house_x', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('house_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'house_y')
    op.drop_column('users', 'house_x')
    op.drop_column('users', 'island_seed')
    op.drop_index('ix_direct_messages_session_created', table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index('ix_visit_sessions_visitor_active', table_name='visit_sessions')
    op.drop_index('ix_visit_sessions_host_active', table_name='visit_sessions')
    op.drop_table('visit_sessions')
    # ### end Alembic commands ###
